openapi: "3.0.0"
info:
  title: MLA Animal Health and Treatments example
  version: 0.0.1
paths:
  /animal/{identifier}/treatments:
    get:
      description: Returns the treatments for the specified animal
      operationId: findTreatments
      parameters:
        - name: identifier
          in: path
          description: primary identifier for the animal
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Treatments response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://github.com/AndyDe-Aldent/animal_schema/blob/feature/LifeDataSwaggerSpec/JSON_Schemas/Animal_Health_and_Treatments/iscTreatmentEvent'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Uploads new treatment event for the animal
      operationId: addTreatment
      parameters:
        - name: identifier
          in: path
          description: primary identifier for the animal
          required: true
          schema:
            type: string
      requestBody:
        description: new treatment event for the animal
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://github.com/AndyDe-Aldent/animal_schema/blob/feature/LifeDataSwaggerSpec/JSON_Schemas/Animal_Health_and_Treatments/iscTreatmentEvent'
      responses:
        '200':
          description: animal response
          content:
            application/json:
              schema:
                $ref: 'https://github.com/AndyDe-Aldent/animal_schema/blob/feature/LifeDataSwaggerSpec/JSON_Schemas/Animal_Health_and_Treatments/iscTreatmentEvent'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Updates the treatment event for the specified animal
      operationId: updateTreatment
      parameters:
        - name: identifier
          in: path
          description: primary identifier for the animal
          required: true
          schema:
            type: string
      requestBody:
        description: Updated treatment event for the animal
        required: true
        content:
          application/json:
            schema:
              $ref: 'https://github.com/AndyDe-Aldent/animal_schema/blob/feature/LifeDataSwaggerSpec/JSON_Schemas/Weights_and_Condition_Scores/iscScoreReference'
      responses:
        '200':
          description: animal response
          content:
            application/json:
              schema:
                $ref: 'https://github.com/AndyDe-Aldent/animal_schema/blob/feature/LifeDataSwaggerSpec/JSON_Schemas/Weights_and_Condition_Scores/iscScoreReference'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: deletes a single animal based on the ID supplied
      operationId: deleteAnimal
      parameters:
        - name: identifier
          in: path
          description: primary identifier for the animal to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: animal deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /farm/{id}/animals:
    parameters:
      - name: id
        in: path
        description: primary identifier for the farm
        required: true
        schema:
          type: string
    get:
      description: Returns the list of animals for the farm
      operationId: findAnimals
      responses:
        '200':
          description: animal response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://github.com/AndyDe-Aldent/animal_schema/blob/feature/LifeDataSwaggerSpec/JSON_Schemas/Identity_And_Life_Data/iscAnimalCore.json'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates new animals for the farm
      operationId: addAnimals
      requestBody:
        description: Animals to add to the farm
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: 'https://github.com/AndyDe-Aldent/animal_schema/blob/feature/LifeDataSwaggerSpec/JSON_Schemas/Identity_And_Life_Data/iscAnimalCore.json'
      responses:
        '200':
          description: animals response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://github.com/AndyDe-Aldent/animal_schema/blob/feature/LifeDataSwaggerSpec/JSON_Schemas/Identity_And_Life_Data/iscAnimalCore.json'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string