openapi: "3.0.0"
info:
  title: MLA Identity And Life Data Example
  version: 0.0.1
paths:
  /animal:
    get:
      description: |
        Returns the details for the specified animal
      operationId: findPets
      parameters:
        - name: identifier
          in: query
          description: primary identifier for the animal
          required: true
          schema:
            type: string
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                  $ref: '#/iscAnimalCore'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      description: Updates the specified animal
      operationId: updateAnimal
      parameters:
        - name: identifier
          in: query
          description: primary identifier for the animal
          required: true
          schema:
            type: string
      requestBody:
        description: Updated details for the animal
        required: true
        content:
          application/json:
            schema:
              $ref: '#/iscAnimalCore'
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/iscAnimalCore'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets/{id}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the pet
      operationId: find pet by id
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: pet response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: deletes a single pet based on the ID supplied
      operationId: deletePet
      parameters:
        - name: id
          in: path
          description: ID of pet to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: pet deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      allOf:
        - $ref: '#/components/schemas/NewPet'
        - type: object
          required:
          - id
          properties:
            id:
              type: integer
              format: int64

    NewPet:
      type: object
      required:
        - name  
      properties:
        name:
          type: string
        tag:
          type: string    

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string